- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: installing the file beat 
  ansible.builtin.yum:
    name: filebeat
    state: installed