- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: installing the file beat 
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: file beat copy
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: start file
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true