- name: copying the conf file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: restart systemd file
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true
