- name: adding the application user
  ansible.builtin.user:
    name: "{{app_user}}"

- name: remove the old directory
  ansible.builtin.file:
    path: /app 
    state: absent

- name: create the new directory
  ansible.builtin.file:
    path: /app 
    state: directory

- name: downlading the code file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
