- name: installing maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: copying the file
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: cleaning maven 
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: copying the scheme fun
  ansible.builtin.import_tasks:
    file: schema_fun.yml

- name: copying the systemd file
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: importing the role prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_expoter

