- name: installing the repo for the node
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: installing nodejs repo
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: copy file of app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: npm install
  ansible.builtin.shell: npm install
  args:
    chdir: /app
    
- name: copy file of schema_fun
  ansible.builtin.import_tasks:
    file: schema_fun.yml

- name: copy file of systemd
  ansible.builtin.import_tasks:
    file: systemd_setup.yml