
- name: installing the python package
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python-devel
    state: installed

- name: copy the file 
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: installing the pip3.6
  ansible.builtin.yum:
    name: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: checking the password
  ansible.builtin.shell: sed -i -e "s|rabbit_user_passwd|$rabbit_user_passwd|" ${script_path}/payment.service

- name: copy file of systemd
  ansible.builtin.import_tasks:
    file: systemd_setup.yml