
- name: installing the python package
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: copy the file 
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: installing the pip3.6
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: copy file of systemd
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: importing the role prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_expoter