- name: load scheme mongodb
  when: schema_fun == "mongo"
  block:
    - name: copying repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: installing mongo_client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: loading scheme
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.mongodb.scheme_repo_url', region='us-east-1' ) }} </app/schema/{{component}}.js

- name: load scheme mysql
  when: schema_fun == "mysql"
  block:
    - name: installing the mysql client
      ansible.builtin.yum:
        name: mysql
        state: installed
    
    - name: loading the scheme
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'dev.mysql.url_schema', region='us-east-1' ) }} -uroot -p{{ lookup('aws_ssm', 'dev.mysql.root_passwd', region='us-east-1' ) }} < /app/schema/shipping.sql