- name: copying the systemsetup file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: start a {{ component }} service
  ansible.builtin.systemd:
    name: {{ component }}
    state: restarted
    enabled: true
    deamon_reload: true